name: controllable-latent-diffusion
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - pip
  - numpy==1.26.4
  - pip:
      - resolv-pipelines @ git+ssh://git@github.com/resolv-libs/resolv-pipelines.git@main
      - git+ssh://git@github.com/resolv-libs/resolv-ml.git@main
